### ISSUE TITLE
Can't find on macOS

### ISSUE THREAD

**Issue by librasteve** [antononcube/Raku-Jupyter-Chatbook#2]
I am on macOS Sequoia 15.0.1 (M1), Python 3.12.4, Raku 2024.08

I followed the getting started like this:

zef install Jupyter::Chatbook --force-install
brew install zmq
sudo cp /opt/homebrew/lib/libzmq.5.dylib /usr/local/lib
jupyter-chatbook.raku --generate-config --force

```
Creating directory /Users/stephenroe/.local/share/jupyter/kernels/raku
Writing kernel.json to /Users/stephenroe/.local/share/jupyter/kernels/raku/kernel.json
Copying logo-32x32.png to /Users/stephenroe/.local/share/jupyter/kernels/raku
Copying logo-64x64.png to /Users/stephenroe/.local/share/jupyter/kernels/raku
Congratulations, configuration files have been successfully written!
Happy Chatting! <- jupyter console --kernel=raku
```

seems OK to here

BUT jupyter console --kernel=raku

gives this error:

```
~ > jupyter console --kernel=raku                  
[ZMQTerminalIPythonApp] WARNING | Kernelspec name raku cannot be found!
[ZMQTerminalIPythonApp] ERROR | No such kernel named raku
Traceback (most recent call last):
  File "/Library/Python/3.9/site-packages/jupyter_client/manager.py", line 87, in wrapper
    out = await method(self, *args, **kwargs)
  File "/Library/Python/3.9/site-packages/jupyter_client/manager.py", line 435, in _async_start_kernel
    kernel_cmd, kw = await self._async_pre_start_kernel(**kw)
  File "/Library/Python/3.9/site-packages/jupyter_client/manager.py", line 397, in _async_pre_start_kernel
    self.kernel_spec,
  File "/Library/Python/3.9/site-packages/jupyter_client/manager.py", line 195, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
  File "/Library/Python/3.9/site-packages/jupyter_client/kernelspec.py", line 285, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named raku
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-console", line 8, in <module>
    sys.exit(main())
  File "/Library/Python/3.9/site-packages/jupyter_core/application.py", line 283, in launch_instance
    super().launch_instance(argv=argv, **kwargs)
  File "/Library/Python/3.9/site-packages/traitlets/config/application.py", line 1074, in launch_instance
    app.initialize(argv)
  File "/Library/Python/3.9/site-packages/traitlets/config/application.py", line 118, in inner
    return method(app, *args, **kwargs)
  File "/Library/Python/3.9/site-packages/jupyter_console/app.py", line 136, in initialize
    self.init_shell()
  File "/Library/Python/3.9/site-packages/jupyter_console/app.py", line 103, in init_shell
    JupyterConsoleApp.initialize(self)
  File "/Library/Python/3.9/site-packages/jupyter_client/consoleapp.py", line 364, in initialize
    self.init_kernel_manager()
  File "/Library/Python/3.9/site-packages/jupyter_client/consoleapp.py", line 317, in init_kernel_manager
    self.kernel_manager.start_kernel(**kwargs)
  File "/Library/Python/3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Library/Python/3.9/site-packages/jupyter_client/manager.py", line 96, in wrapper
    raise e
  File "/Library/Python/3.9/site-packages/jupyter_client/manager.py", line 87, in wrapper
    out = await method(self, *args, **kwargs)
  File "/Library/Python/3.9/site-packages/jupyter_client/manager.py", line 435, in _async_start_kernel
    kernel_cmd, kw = await self._async_pre_start_kernel(**kw)
  File "/Library/Python/3.9/site-packages/jupyter_client/manager.py", line 397, in _async_pre_start_kernel
    self.kernel_spec,
  File "/Library/Python/3.9/site-packages/jupyter_client/manager.py", line 195, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
  File "/Library/Python/3.9/site-packages/jupyter_client/kernelspec.py", line 285, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named raku
```

**Comment by antononcube** [comment]
Can you otherwise use the Jupyter Raku kernel? I.e. not from the console. (Via a web browser, or VS Code, or JupyterLab.)

**Comment by librasteve** [comment]
I just tried (per the Jupyter::Chatbook README.md...:

```
zef install Jupyter::Chatbook --force-install
jupyter-chatbook.raku --generate-config --force
jupyter-notebook
```

The notebook works fine for New>Python3 kernel. No New>Raku kernel option is shown.

The errors I show above ^^ come from the command `jupyter console --kernel=raku`

**Comment by librasteve** [comment]
So I have 

```
 jupyter-kernel.raku --generate-config --force                  
Creating directory /Users/xxx/.local/share/jupyter/kernels/raku
Writing kernel.json to /Users/xxx/.local/share/jupyter/kernels/raku/kernel.json
Copying logo-32x32.png to /Users/xxx/.local/share/jupyter/kernels/raku
Copying logo-64x64.png to /Users/xxx/.local/share/jupyter/kernels/raku
Congratulations, configuration files have been successfully written!
Happy Perling! <- jupyter console --kernel=raku
```

And 
```
~ > jupyter kernelspec list                      
Available kernels:
  python3    /opt/homebrew/lib/python3.9/site-packages/ipykernel/resources
```

fwiw I tried to `cp` the first file into the second dir, but no success

**Comment by librasteve** [comment]
in Paths.rakumod line 14

`when .name eq 'macosx' {`

should be

`when .name eq 'macos' {`

**Comment by librasteve** [comment]
when this is closed, I can apply to vanilla Jupyter::Kernel

**Comment by antononcube** [comment]
I merged the proposed related changes and uploaded to raku.land the new version (with those changes applied): https://raku.land/zef:antononcube/Jupyter::Chatbook .
